### ISSUE TITLE
about cross validation 

### ISSUE THREAD

**Issue by Heyam91** [SaNjAy-143-u/google_colab#2]
Thank you for sharing your amazing modification, I am beginner in deep learning :)
when i am turned cross validation to false, my data are divided into training, validation and testing. say 100 training samples and 50 validation sample. after each 5 epoch, 50 validation sample is used to validate my model performance. my question is in every epoch we use same training and validation data?? or they changed randomly in every epoch? if yes then we use cross validation or not? i am confused in this point.

Thanks in advance :)

**Comment by Sanjay126** [comment]
We are using the same validation and training data and we are not back-propagating to update weights while validating. If we change training and validation data randomly then there is no point of validation as ultimately network would have seen all our examples and will predict almost accurately for them. I have used cross-validation to check different models and compare them how they will perform in general scenario.
